const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const DAY_LABELS={'2026-09-21':'Seg 21','2026-09-22':'Ter 22','2026-09-23':'Qua 23','2026-09-24':'Qui 24'};
const DEFAULT_PREFS={stakeholders:['Petrobras','EPE','ANP','IBP','Shell','bp','TotalEnergies','Equinor','ExxonMobil','Chevron','PRIO','Brava Energia','PetroReconcavo','Transpetro','Google','Microsoft','AWS','NVIDIA'],technologies:['inteligência artificial','IA','AI','digitalização','digital twin','gêmeo digital','analytics','machine learning','OT','cybersecurity','automação','dados','IoT','manutenção preditiva','confiabilidade','asset management','MES','MOM','BIM','knowledge graph','cloud','SAP'],challenges:['eficiência operacional','confiabilidade','disponibilidade','produtividade','transição energética','descarbonização','supply chain','segurança energética','redução de custos','offshore','integridade','manutenção','CAPEX','OPEX','emissões','projetos','logística']};
const SENIORITY=[['CEO',24],['PRESIDENTE',22],['PRESIDENT',22],['DIRETOR EXECUTIVO',20],['EXECUTIVE VICE',20],['VP',18],['VICE-PRESIDENTE',18],['DIRETOR',16],['DIRECTOR',16],['GERENTE EXECUTIVO',14],['HEAD',13],['GERENTE GERAL',13],['GERENTE',9],['MANAGER',9],['COORDENADOR',5]];
const WINDOW_START_TOLERANCE_MIN=20;
let events=[], exhibitors=[], favorites=new Set(JSON.parse(localStorage.getItem('roge_favorites')||'[]')), radar='all', chip='';
let prefs=loadPrefs();
function loadPrefs(){try{return {...DEFAULT_PREFS,...JSON.parse(localStorage.getItem('roge_prefs')||'{}')}}catch{return structuredClone(DEFAULT_PREFS)}}
function norm(s=''){return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
function uniq(a){return [...new Set(a.filter(Boolean))]}
function textOf(e){return norm([e.title,e.track,e.type,e.location,e.speakers_raw,...(e.speakers||[]).map(x=>`${x.name} ${x.detail}`)].join(' '))}
function containsAny(txt,arr){return arr.filter(k=>{const n=norm(k).trim();if(!n)return false;if(n.length<=3)return new RegExp(`(^|[^a-z0-9])${n.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}([^a-z0-9]|$)`,'i').test(txt);return txt.includes(n)})}
function scoreEvent(e){const txt=textOf(e);const stakeholderHits=containsAny(txt,prefs.stakeholders);const techHits=containsAny(txt,prefs.technologies);const challengeHits=containsAny(txt,prefs.challenges);let senior=0;for(const [k,v] of SENIORITY){if(txt.includes(norm(k))) senior=Math.max(senior,v)}let stakeholder=Math.min(100,stakeholderHits.length*22+senior+(txt.includes('petrobras')?18:0));let technology=Math.min(100,techHits.length*18+(txt.includes('inteligencia artificial')||txt.match(/\bia\b/)?12:0));let challenge=Math.min(100,challengeHits.length*17);let networking=0;if(/meetings|forum|fórum|fest|happy|luncheon|cocktail|network/i.test(e.track+' '+e.title+' '+e.type))networking=82;else if(stakeholderHits.length)networking=55;let total=Math.round(stakeholder*.46+technology*.32+challenge*.17+networking*.05);if(e.type==='Exposição')total=Math.max(total,35);if(e.type==='ROG.e FEST')total=Math.max(total,45);const priority=total>=55?'P2':total>=35?'P3':'P4';return {stakeholder,technology,challenge,networking,total,priority,isTopWindow:false,windowStart:'',windowEnd:'',stakeholderHits,techHits,challengeHits}}
function timeToMinutes(value=''){const m=/^(\d{1,2}):(\d{2})$/.exec(value);return m?Number(m[1])*60+Number(m[2]):Number.POSITIVE_INFINITY}
function compareFit(a,b){return (b._score.total-a._score.total)||(b._score.stakeholder-a._score.stakeholder)||(b._score.technology-a._score.technology)||(b._score.challenge-a._score.challenge)||norm(a.title).localeCompare(norm(b.title))}
function enriched(){const list=events.map(e=>({...e,_score:scoreEvent(e)}));const dates=uniq(list.map(e=>e.date));for(const date of dates){const timed=list.filter(e=>e.date===date&&e.start&&e.type!=='Exposição').sort((a,b)=>timeToMinutes(a.start)-timeToMinutes(b.start)||compareFit(a,b));let i=0;while(i<timed.length){const anchor=timeToMinutes(timed[i].start);let j=i+1;while(j<timed.length&&timeToMinutes(timed[j].start)-anchor<=WINDOW_START_TOLERANCE_MIN)j++;const windowEvents=timed.slice(i,j);const winner=[...windowEvents].sort(compareFit)[0];const windowEnd=windowEvents.map(e=>e.end).filter(Boolean).sort().at(-1)||'';for(const e of windowEvents){e._score.windowStart=timed[i].start;e._score.windowEnd=windowEnd;e._score.isTopWindow=e.id===winner.id;if(e._score.isTopWindow)e._score.priority='P1'}i=j}}return list}
function fmtDate(d){return DAY_LABELS[d]||d}
function byId(id){return events.find(e=>e.id===id)}
function scoreById(id){return enriched().find(e=>e.id===id)?._score||scoreEvent(byId(id)||{})}
function saveFav(){localStorage.setItem('roge_favorites',JSON.stringify([...favorites]));render()}
function toggleFav(id){favorites.has(id)?favorites.delete(id):favorites.add(id);saveFav()}
function populateFilters(){const day=$('#dayFilter'),type=$('#typeFilter'),loc=$('#locationFilter');uniq(events.map(e=>e.date)).sort().forEach(v=>day.insertAdjacentHTML('beforeend',`<option value="${v}">${fmtDate(v)}</option>`));uniq(events.map(e=>e.type)).sort().forEach(v=>type.insertAdjacentHTML('beforeend',`<option>${escapeHtml(v)}</option>`));uniq(events.map(e=>e.location)).sort().forEach(v=>loc.insertAdjacentHTML('beforeend',`<option>${escapeHtml(v)}</option>`));const defaultChips=['Petrobras','IA / AI','Digitalização','Digital Twin','OT / Cyber','Confiabilidade','Supply Chain','Transição Energética','Offshore','ROG.e FEST'];$('#smartChips').innerHTML=defaultChips.map(c=>`<button class="chip" data-chip="${c}">${c}</button>`).join('')}
function chipTerms(c){return {'IA / AI':['inteligencia artificial','artificial intelligence','machine learning','analytics','generative ai','ia generativa'],'Digitalização':['digitalizacao','digital transformation'],'Digital Twin':['digital twin','gemeo digital'],'OT / Cyber':[' ot ','cyber','ciber'],'Confiabilidade':['confiabilidade','preditiv','manutencao'],'Supply Chain':['supply chain','suprimentos','compras'],'Transição Energética':['transicao energetica','descarbon','renovav','hidrogenio'],'Offshore':['offshore','subsea','pocos','reservas'],'ROG.e FEST':['rog.e fest','happy hour']}[c]||[norm(c)]}
