function icsDate(date,time){return date.replaceAll('-','')+'T'+(time||'10:00').replace(':','')+'00'}
function escICS(s=''){return String(s).replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;')}
function downloadICS(list,name='ROGe-2026.ics'){
  if(!list.length)return;
  const ics=PlannerModel.buildICS(list,teamData.assignments);
  const a=document.createElement('a');
  a.href=URL.createObjectURL(new Blob([ics],{type:'text/calendar;charset=utf-8'}));
  a.download=name;document.body.appendChild(a);a.click();a.remove();
  setTimeout(()=>URL.revokeObjectURL(a.href),1000);
}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fillRadarForm(){$('#stakeholderPrefs').value=prefs.stakeholders.join(', ');$('#technologyPrefs').value=prefs.technologies.join(', ');$('#challengePrefs').value=prefs.challenges.join(', ');$('#roomPrefs').value=(prefs.rooms||DEFAULT_PREFS.rooms).join(', ');$('#rolePrefs').value=(prefs.roles||DEFAULT_PREFS.roles).join(', ')}
function wire(){['search','dayFilter','typeFilter','priorityFilter','locationFilter','onlyMine','sort'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',render));$('#exhibitorSearch').addEventListener('input',renderExhibitors);$$('.radar-card').forEach(b=>b.onclick=()=>{$$('.radar-card').forEach(x=>x.classList.remove('active'));b.classList.add('active');radar=b.dataset.radar;render()});$('#smartChips').onclick=e=>{if(!e.target.matches('.chip'))return;const c=e.target.dataset.chip;chip=chip===c?'':c;$$('.chip').forEach(x=>x.classList.toggle('active',x.dataset.chip===chip));render()};$('#downloadMine').onclick=$('#calendarBtn').onclick=()=>downloadICS([...favorites].map(byId).filter(Boolean),'Minha-Agenda-ROGe-2026.ics');$('#editRadarBtn').onclick=()=>{fillRadarForm();$('#radarModal').showModal()};$('#radarForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;prefs={stakeholders:$('#stakeholderPrefs').value.split(',').map(x=>x.trim()).filter(Boolean),technologies:$('#technologyPrefs').value.split(',').map(x=>x.trim()).filter(Boolean),challenges:$('#challengePrefs').value.split(',').map(x=>x.trim()).filter(Boolean),rooms:$('#roomPrefs').value.split(',').map(x=>x.trim()).filter(Boolean),roles:$('#rolePrefs').value.split(',').map(x=>x.trim()).filter(Boolean)};localStorage.setItem('roge_prefs',JSON.stringify(prefs));render()});$('#resetRadar').onclick=()=>{prefs=structuredClone(DEFAULT_PREFS);localStorage.removeItem('roge_prefs');fillRadarForm();render()}}
async function init(){try{const [er,ex]=await Promise.all([fetch(`data/events.json?v=${Date.now()}`),fetch(`data/exhibitors.json?v=${Date.now()}`)]);const ed=await er.json();const xd=await ex.json();events=ed.events||[];exhibitors=xd.exhibitors||[];$('#syncState').textContent=events.length?'Agenda sincronizada':'Aguardando sincronização';$('#lastUpdate').textContent=ed.generated_at?`Atualizado ${new Date(ed.generated_at).toLocaleString('pt-BR')}`:'Fonte oficial ROG.e';populateFilters();wire();wireTeam();wireMaps();render()}catch(err){console.error(err);$('#syncState').textContent='Falha ao carregar dados';$('#lastUpdate').textContent='Tente atualizar a página'}}
init();
